[project]
name = "ln-cli"
version = "0.1.0"
description = "Lunar é um CLI para ajudar com rotinas relaciondas ao python"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    {name = "rodrigo8064",email = "rodrigooliveiradel@gmail.com"}
]
readme = "README.md"
packages = [{include = "ln_cli"}]
classifiers = [
    "Environment :: Console",
    "Natural Language :: Portuguese (Brazilian)",
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.13, <4.0"
dependencies = [
    "typer[all] (>=0.27.0,<0.28.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
lunar = "ln_cli.cli:app"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "taskipy (>=1.14.1,<2.0.0)",
    "ruff (>=0.15.22,<0.16.0)",
]
doc = [
    "mkdocs-material (>=9.7.7,<10.0.0)",
    "mkdocstrings (>=1.0.6,<2.0.0)",
    "mkdocstrings-python (>=2.0.5,<3.0.0)",
    "mkdocs-macros-plugin (>=1.5.0,<2.0.0)"
]

[tool.poetry.urls]
"Documentação" = "https://ln-cli.readthedocs.io/pt-br/latest/"
"Código" = "https://github.com/Rodrigo8064/ln-cli"

[tool.ruff]
line-length = 79

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.pytest.ini_options]
pythonpath = "."

[tool.taskipy.tasks]
lint = 'ruff check'
docs = "mkdocs serve"
pre_format = 'ruff check --fix'
format = 'ruff format'
pre_test = 'task lint'
test = "pytest -s -x --cov=ln_cli -vv"
post_test = "coverage html"
