name: pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v6

      - name: Instalar o python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Instalar o poetry
        run: pip install poetry

      - name: Instalar dependências
        run: poetry install --without doc

      - name: Executar testes
        run: poetry run task test
